import { definePreset } from "@pandacss/dev";
import {
  colors,
  spacing,
  padding,
  radii,
  shadows,
  typography,
  bg,
  text,
  action,
  status,
  border,
} from "@billabex/ui-tokens";

export const billabexPreset = definePreset({
  name: "billabex",
  theme: {
    tokens: {
      colors: {
        "solid.white": { value: colors.solid.white.hex },
        "solid.black": { value: colors.solid.black.hex },
        "neutral.50": { value: colors.neutral[50].hex },
        "neutral.100": { value: colors.neutral[100].hex },
        "neutral.200": { value: colors.neutral[200].hex },
        "neutral.300": { value: colors.neutral[300].hex },
        "neutral.400": { value: colors.neutral[400].hex },
        "neutral.500": { value: colors.neutral[500].hex },
        "neutral.600": { value: colors.neutral[600].hex },
        "neutral.700": { value: colors.neutral[700].hex },
        "gold.100": { value: colors.gold[100].hex },
        "gold.300": { value: colors.gold[300].hex },
        "gold.500": { value: colors.gold[500].hex },
        "terracotta.300": { value: colors.terracotta[300].hex },
        "terracotta.400": { value: colors.terracotta[400].hex },
        "terracotta.500": { value: colors.terracotta[500].hex },
        "green.50": { value: colors.green[50].hex },
        "green.600": { value: colors.green[600].hex },
        "orange.50": { value: colors.orange[50].hex },
        "orange.500": { value: colors.orange[500].hex },
        "red.50": { value: colors.red[50].hex },
        "red.600": { value: colors.red[600].hex },
        "blue.50": { value: colors.blue[50].hex },
        "blue.700": { value: colors.blue[700].hex },
      },
      spacing: {
        "3xs": { value: spacing["3xs"].px },
        xs: { value: spacing.xs.px },
        sm: { value: spacing.sm.px },
        md: { value: spacing.md.px },
        lg: { value: spacing.lg.px },
        xl: { value: spacing.xl.px },
        "2xl": { value: spacing["2xl"].px },
        "3xl": { value: spacing["3xl"].px },
        "4xl": { value: spacing["4xl"].px },
        "5xl": { value: spacing["5xl"].px },
        "6xl": { value: spacing["6xl"].px },
        "padding.card": { value: padding.card.px },
        "padding.page": { value: padding.page.px },
      },
      sizes: {
        "3xs": { value: spacing["3xs"].px },
        xs: { value: spacing.xs.px },
        sm: { value: spacing.sm.px },
        md: { value: spacing.md.px },
        lg: { value: spacing.lg.px },
        xl: { value: spacing.xl.px },
        "2xl": { value: spacing["2xl"].px },
        "3xl": { value: spacing["3xl"].px },
        "4xl": { value: spacing["4xl"].px },
        "5xl": { value: spacing["5xl"].px },
        "6xl": { value: spacing["6xl"].px },
      },
      radii: {
        none: { value: radii.none.px },
        xs: { value: radii.xs.px },
        sm: { value: radii.sm.px },
        md: { value: radii.md.px },
        lg: { value: radii.lg.px },
        full: { value: radii.full.px },
      },
      shadows: {
        sm: { value: shadows.sm.css },
        md: { value: shadows.md.css },
        lg: { value: shadows.lg.css },
      },
      fonts: {
        body: { value: typography.body.fontFamily },
      },
      fontSizes: {
        display: { value: typography.display.fontSize.px },
        "headline.lg": { value: typography.headlineLg.fontSize.px },
        "headline.md": { value: typography.headlineMd.fontSize.px },
        "headline.sm": { value: typography.headlineSm.fontSize.px },
        body: { value: typography.body.fontSize.px },
        "body.sm": { value: typography.bodySm.fontSize.px },
        caption: { value: typography.caption.fontSize.px },
        "caption.soft": { value: typography.captionSoft.fontSize.px },
        "caption.xs": { value: typography.captionXs.fontSize.px },
        micro: { value: typography.micro.fontSize.px },
      },
      fontWeights: {
        regular: { value: "400" },
        medium: { value: "500" },
        semibold: { value: "600" },
      },
      lineHeights: {
        display: { value: typography.display.lineHeight.px },
        "headline.lg": { value: typography.headlineLg.lineHeight.px },
        "headline.md": { value: typography.headlineMd.lineHeight.px },
        "headline.sm": { value: typography.headlineSm.lineHeight.px },
        body: { value: typography.body.lineHeight.px },
        "body.sm": { value: typography.bodySm.lineHeight.px },
        caption: { value: typography.caption.lineHeight.px },
        "caption.soft": { value: typography.captionSoft.lineHeight.px },
        "caption.xs": { value: typography.captionXs.lineHeight.px },
        micro: { value: typography.micro.lineHeight.px },
      },
    },
    semanticTokens: {
      colors: {
        "bg.default": { value: bg.default.hex },
        "bg.subtle": { value: bg.subtle.hex },
        "bg.muted": { value: bg.muted.hex },
        "bg.inverse": { value: bg.inverse.hex },
        "bg.brand": { value: bg.brand.hex },
        "bg.accent": { value: bg.accent.hex },
        "text.primary": { value: text.primary.hex },
        "text.secondary": { value: text.secondary.hex },
        "text.tertiary": { value: text.tertiary.hex },
        "text.inverse": { value: text.inverse.hex },
        "text.link": { value: text.link.hex },
        "text.linkHover": { value: text.linkHover.hex },
        "action.primary": { value: action.primary.hex },
        "action.primaryHover": { value: action.primaryHover.hex },
        "action.primaryPressed": { value: action.primaryPressed.hex },
        "action.secondary": { value: action.secondary.hex },
        "action.secondaryHover": { value: action.secondaryHover.hex },
        "action.destructive": { value: action.destructive.hex },
        "status.success": { value: status.success.hex },
        "status.successSubtle": { value: status.successSubtle.hex },
        "status.warning": { value: status.warning.hex },
        "status.warningSubtle": { value: status.warningSubtle.hex },
        "status.error": { value: status.error.hex },
        "status.errorSubtle": { value: status.errorSubtle.hex },
        "status.info": { value: status.info.hex },
        "status.infoSubtle": { value: status.infoSubtle.hex },
        "border.default": { value: border.default.hex },
        "border.subtle": { value: border.subtle.hex },
        "border.focus": { value: border.focus.hex },
        "border.error": { value: border.error.hex },
      },
    },
  },
  conditions: {
    extend: {
      smDown: "@media (max-width: 349px)",
      sm: "@media (min-width: 350px)",
      md: "@media (min-width: 390px)",
      lg: "@media (min-width: 480px)",
      tablet: "@media (min-width: 768px)",
      desktop: "@media (min-width: 1024px)",
      desktopMd: "@media (min-width: 1280px)",
      desktopLg: "@media (min-width: 1440px)",
      desktopXl: "@media (min-width: 1920px)",
    },
  },
});
